# ==========================================
# Base Environment
# ==========================================
FROM ubuntu:24.04 AS base

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    curl \
    lsb-release \
    liburdfdom-dev \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/apt/keyrings && \
    curl http://robotpkg.openrobots.org/packages/debian/robotpkg.asc | tee /etc/apt/keyrings/robotpkg.asc && \
    echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/robotpkg.asc] http://robotpkg.openrobots.org/packages/debian/pub $(lsb_release -cs) robotpkg" | tee /etc/apt/sources.list.d/robotpkg.list

RUN apt-get update && apt-get install -y \
    robotpkg-eigen3 \
    robotpkg-coal \
    && rm -rf /var/lib/apt/lists/*

ENV PATH=/opt/openrobots/bin:$PATH
ENV PKG_CONFIG_PATH=/opt/openrobots/lib/pkgconfig:$PKG_CONFIG_PATH
ENV LD_LIBRARY_PATH=/opt/openrobots/lib:$LD_LIBRARY_PATH
ENV PYTHONPATH=/opt/openrobots/lib/python3.12/site-packages:$PYTHONPATH
ENV CMAKE_PREFIX_PATH=/opt/openrobots:$CMAKE_PREFIX_PATH

WORKDIR /krlsim

# ==========================================
# Development Stage
# ==========================================
FROM base AS dev
CMD ["/bin/bash"]

# # ==========================================
# # Production Stage
# # ==========================================
# FROM ubuntu:24.04 AS production

# ENV DEBIAN_FRONTEND=noninteractive
# ENV PYTHONUNBUFFERED=1

# RUN apt-get update && apt-get install -y --no-install-recommends \
#     python3 \
#     libgomp1 \
#     liburdfdom-dev \
#     && rm -rf /var/lib/apt/lists/*

# COPY --from=builder /opt/openrobots /opt/openrobots
# COPY --from=builder /opt/venv /opt/venv
# COPY --from=builder /krlsim /krlsim

# ENV PATH=/opt/openrobots/bin:$PATH
# ENV PKG_CONFIG_PATH=/opt/openrobots/lib/pkgconfig:$PKG_CONFIG_PATH
# ENV LD_LIBRARY_PATH=/opt/openrobots/lib:$LD_LIBRARY_PATH
# ENV CMAKE_PREFIX_PATH=/opt/openrobots:$CMAKE_PREFIX_PATH
# ENV PATH="/opt/venv/bin:$PATH"

# WORKDIR /krlsim
# CMD ["pytest", "tests/python/"]